# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - rre-test

on:
  push:
    branches:
      - copilot/fix-2703cec8-076c-4633-b622-d4d3fbc2569f
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'rre-test'
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '22.x'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
     
      - name: Verify build output
        run: |
          ls -la .next/
          echo "Build completed successfully"

      - name: Prepare for deployment
        run: |
          # Create a clean package.json for production
          node -e "
          const pkg = require('./package.json');
          delete pkg.devDependencies;
          delete pkg.scripts.dev;
          require('fs').writeFileSync('./package.json', JSON.stringify(pkg, null, 2));
          "
          
          # Remove unnecessary files
          rm -rf .git
          rm -rf .github
          rm -rf node_modules/.cache
          rm -rf .next/cache
          rm -rf src
          rm -f *.md
          rm -f *.config.js
          rm -f tsconfig.json

      - name: Reinstall production dependencies
        run: |
          rm -rf node_modules
          npm install --production
          # Verify Next.js is still properly installed
          npx next --version
          ls -la node_modules/next/dist/server/

      - name: Create deployment package
        run: |
          zip -r release.zip . -x \
            "*.git*" \
            ".next/cache/*" \
            "node_modules/.cache/*" \
            "*.log"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_34B7927A69724390BEE59FB26EEF9F33 }}